#!/bin/sh

MIN_TOKENS='1'
export MIN_TOKENS

STRIDE='0'
export STRIDE

SIMILARITY='1'
export SIMILARITY

SRC_DIR="../../execution/materializer"
export SRC_DIR

FILE_PATTERN="*.java"
export FILE_PATTERN

DECKARD_DIR="tool"
export DECKARD_DIR

VECTOR_DIR="../../execution/measurer/vectors"
export VECTOR_DIR

CLUSTER_DIR="../../execution/measurer/cluster"
export CLUSTER_DIR

TIME_DIR="../../execution/measurer/times"
export TIME_DIR

VGEN_EXEC="$DECKARD_DIR/src/main/jvecgen"
export GROUPING_EXEC

GROUPING_EXEC="$DECKARD_DIR/src/vgen/vgrouping/runvectorsort"
export GROUPING_EXEC

CLUSTER_EXEC="$DECKARD_DIR/src/lsh/bin/enumBuckets"
export CLUSTER_EXEC

QUERY_EXEC="$DECKARD_DIR/src/lsh/bin/queryBuckets"
export QUERY_EXEC

POSTPRO_EXEC="$DECKARD_DIR/scripts/clonedetect/post_process_groupfile"
export POSTPRO_EXEC

GROUPING_S='1'
export GROUPING_S

MAX_PROC='1'
export MAX_PROCS
