#!/bin/sh
export MIN_TOKENS=1
export STRIDE=0
export SIMILARITY=1.0
export SRC_DIR=../../execution/materializer
export FILE_PATTERN=*.java
export VECTOR_DIR=../../execution/measurer/vectors
export CLUSTER_DIR=../../execution/measurer/cluster
export TIME_DIR=../../execution/measurer/times
export DECKARD_DIR=tool
export VGEN_EXEC=tool/src/main/jvecgen
export GROUPING_EXEC=tool/src/vgen/vgrouping/runvectorsort
export CLUSTER_EXEC=tool/src/lsh/bin/enumBuckets
export QUERY_EXEC=tool/src/lsh/bin/queryBuckets
export POSTPRO_EXEC=tool/scripts/clonedetect/post_process_groupfile
export GROUPING_S=1
export MAX_PROC=1