#!/bin/sh
export MIN_TOKENS=1
export STRIDE=15
export SIMILARITY=1.0
export FILE_PATTERN=*.java
export SRC_DIR=../../exec/materializer
export VECTOR_DIR=../../exec/measurer/vectors
export CLUSTER_DIR=../../exec/measurer/cluster
export TIME_DIR=../../exec/measurer/times
export DECKARD_DIR=tool
export VGEN_EXEC=tool/src/main/jvecgen
export GROUPING_EXEC=tool/src/vgen/vgrouping/runvectorsort
export CLUSTER_EXEC=tool/src/lsh/bin/enumBuckets
export QUERY_EXEC=tool/src/lsh/bin/queryBuckets
export POSTPRO_EXEC=tool/scripts/clonedetect/post_process_groupfile
export GROUPING_S=1
export MAX_PROCS=1